MODEL:
  NAME: "sequential_angry_fox"
  PRETRAINED_PATH: "storage/checkpoint.h5"
  FILTERS: 24
  NUM_LAYERS: 2
  LORA: True
  DROPOUT_RATE: 0.5
  SEQUENCE_LENGTH: 8192

DATASETS:
  TRAIN_DATA: "dataset/WC_TC-AS/train.csv"

DATALOADER:
  NUM_WORKERS: 128
  MAX_QUEUE_SIZE: 4
  WORKPIECE_LENGTH: 17

SOLVER:
  BASE_LR: 5e-3
  BATCH_SIZE: 32
  MAX_EPOCHS: 64
  WEIGHT_DECAY: 1e-10

TEST:
  WEIGHT: ""
  EVALUATE_ONLY: "off"
  EVALUATE_DATA: "dataset/WC_TC-AS/test.csv"
  LIM_MIN: 0.0085
  LIM_MAX: 0.0615
  LOCATION: [3.4, 13.6]

OUTPUT_DIR: "log/WC_TC-AS"
DESCRIPTION: ""