MODEL:
  NAME: "sequential_angry_fox"
  PRETRAINED_PATH: "storage/checkpoint.h5"
  FILTERS: 24
  NUM_LAYERS: 2
  LORA: True
  DROPOUT_RATE: 0.5
  SEQUENCE_LENGTH: 10240

DATASETS:
  TRAIN_DATA: "dataset/WC_TAN-MS/train.csv"

DATALOADER:
  NUM_WORKERS: 128
  MAX_QUEUE_SIZE: 4
  WORKPIECE_LENGTH: 50

SOLVER:
  BASE_LR: 1e-4
  BATCH_SIZE: 32
  MAX_EPOCHS: 4
  WEIGHT_DECAY: 1e-10

TEST:
  WEIGHT: ""
  EVALUATE_ONLY: "off"
  EVALUATE_DATA: "dataset/WC_TAN-MS/test.csv"
  LIM_MIN: -0.031
  LIM_MAX: 0.022
  LOCATION: [10,30,50]

OUTPUT_DIR: "log/WC_TAN-MS"
DESCRIPTION: ""